/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'clientes': RouteRecordInfo<'clientes', '/clientes', Record<never, never>, Record<never, never>>,
    'codigos-cuenta-gasto': RouteRecordInfo<'codigos-cuenta-gasto', '/codigos-cuenta-gasto', Record<never, never>, Record<never, never>>,
    'entidades': RouteRecordInfo<'entidades', '/entidades', Record<never, never>, Record<never, never>>,
    'extractos': RouteRecordInfo<'extractos', '/extractos', Record<never, never>, Record<never, never>>,
    'extractos-id': RouteRecordInfo<'extractos-id', '/extractos/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'facturas': RouteRecordInfo<'facturas', '/facturas', Record<never, never>, Record<never, never>>,
    'facturas-id': RouteRecordInfo<'facturas-id', '/facturas/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'facturas-conciliacion-extracto-importe': RouteRecordInfo<'facturas-conciliacion-extracto-importe', '/facturas/conciliacion-extracto-importe', Record<never, never>, Record<never, never>>,
    'facturas-subir-ticket': RouteRecordInfo<'facturas-subir-ticket', '/facturas/subir-ticket', Record<never, never>, Record<never, never>>,
    'facturas-emitidas': RouteRecordInfo<'facturas-emitidas', '/facturas-emitidas', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'pagos': RouteRecordInfo<'pagos', '/pagos', Record<never, never>, Record<never, never>>,
    'pagos-conciliacion-conceptos': RouteRecordInfo<'pagos-conciliacion-conceptos', '/pagos/conciliacion-conceptos', Record<never, never>, Record<never, never>>,
    'pagos-extractos-id-conciliacion-preview': RouteRecordInfo<'pagos-extractos-id-conciliacion-preview', '/pagos/extractos/:id/conciliacion/preview', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'pagos-extractos-id-conciliacion-preview-embed': RouteRecordInfo<'pagos-extractos-id-conciliacion-preview-embed', '/pagos/extractos/:id/conciliacion/preview/embed', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'pagos-extractos-id-conciliacion-emitidas-preview': RouteRecordInfo<'pagos-extractos-id-conciliacion-emitidas-preview', '/pagos/extractos/:id/conciliacion-emitidas/preview', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'pagos-extractos-id-conciliacion-emitidas-preview-embed': RouteRecordInfo<'pagos-extractos-id-conciliacion-emitidas-preview-embed', '/pagos/extractos/:id/conciliacion-emitidas/preview/embed', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'pagos-manual': RouteRecordInfo<'pagos-manual', '/pagos/manual', Record<never, never>, Record<never, never>>,
    'pagos-movimientos-bancarios': RouteRecordInfo<'pagos-movimientos-bancarios', '/pagos/movimientos-bancarios', Record<never, never>, Record<never, never>>,
    'pagos-registrados': RouteRecordInfo<'pagos-registrados', '/pagos/registrados', Record<never, never>, Record<never, never>>,
    'proveedores': RouteRecordInfo<'proveedores', '/proveedores', Record<never, never>, Record<never, never>>,
    'proveedores-factura': RouteRecordInfo<'proveedores-factura', '/proveedores-factura', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
    'tipos-pago': RouteRecordInfo<'tipos-pago', '/tipos-pago', Record<never, never>, Record<never, never>>,
    'usuarios': RouteRecordInfo<'usuarios', '/usuarios', Record<never, never>, Record<never, never>>,
  }
}
