/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'clientes': RouteRecordInfo<'clientes', '/clientes', Record<never, never>, Record<never, never>>,
    'codigos-cuenta-gasto': RouteRecordInfo<'codigos-cuenta-gasto', '/codigos-cuenta-gasto', Record<never, never>, Record<never, never>>,
    'entidades': RouteRecordInfo<'entidades', '/entidades', Record<never, never>, Record<never, never>>,
    'extractos': RouteRecordInfo<'extractos', '/extractos', Record<never, never>, Record<never, never>>,
    'extractos-id': RouteRecordInfo<'extractos-id', '/extractos/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'facturas': RouteRecordInfo<'facturas', '/facturas', Record<never, never>, Record<never, never>>,
    'facturas-id': RouteRecordInfo<'facturas-id', '/facturas/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'facturas-emitidas': RouteRecordInfo<'facturas-emitidas', '/facturas-emitidas', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'proveedores': RouteRecordInfo<'proveedores', '/proveedores', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
    'tipos-pago': RouteRecordInfo<'tipos-pago', '/tipos-pago', Record<never, never>, Record<never, never>>,
    'usuarios': RouteRecordInfo<'usuarios', '/usuarios', Record<never, never>, Record<never, never>>,
  }
}
